### ISSUE TITLE
项目拉到本地登录时获取不到验证码

### ISSUE THREAD

**Issue by uaena001** [didnhdj2/my-v3-admin#1]
![image](https://github.com/didnhdj2/my-v3-admin/assets/102605409/05686c77-ae07-44c5-8272-4b1bb32c7510)

**Comment by gqfx** [comment]
你好，本模板刚刚从项目中剥离出来，尚未完善，请勿用于生产

**Comment by didnhdj2** [comment]
> 你好，本模板刚刚从项目中剥离出来，尚未完善，请勿用于生产

**Comment by gqfx** [comment]
已经去掉登录页了
